kind: Service
apiVersion: v1
metadata:
  name: outside-7
  namespace: kafka
spec:
  selector:
    app: kafka
    statefulset.kubernetes.io/pod-name: kafka-7
  ports:
  - protocol: TCP
    targetPort: 9094
    port: 32407
    nodePort: 32407
  type: NodePort