kind: Service
apiVersion: v1
metadata:
  name: outside-8
  namespace: kafka
spec:
  selector:
    app: kafka
    statefulset.kubernetes.io/pod-name: kafka-8
  ports:
  - protocol: TCP
    targetPort: 9094
    port: 32408
    nodePort: 32408
  type: NodePort